name: Translator Test Workflow

on:
  push:
    branches: [ "main" ]
    paths:
      - 'test/unit/test_translator.py'
      - '**.py'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'test/unit/test_translator.py'
      - '**.py'

permissions:
  contents: read

jobs:
  test_translator:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run translator tests
      run: |
        pytest test/unit/test_translator.py
